# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "superQ"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

name: "qmix"

lam: 0.03
alpha: 0.5
ind: 1
mix: 1
expl: 1
dis: 1

goal: "maser"

selected: 'PER_weight' # PER_weight
selected_ratio: 0.9
warm_up: True
selected_ratio_start: 0.8
selected_ratio_end: 1.0
warm_up_ratio: 0.6

selected_alpha: 0.8
selected_epsilon: 0.01
beta_start: 0.8
beta_end: 1

name: "super"
